services:
    database:
        container_name: sellorama_db
        image: postgres:latest
        restart: always
        env_file:
            - .env
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U sr_admin -d sellorama_db"]
            interval: 10s
            timeout: 5s
            retries: 5
        ports:
            - 5432:5432
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            network1:
                ipv4_address: 172.20.0.5
    backend:
        container_name: sellorama_backend
        image: ghcr.io/gautham-kj/sellorama:main
        restart: always
        env_file:
            - .env
        depends_on:
            - database
        ports:
            - 9000:9000
        networks:
            network1:
                ipv4_address: 172.21.0.6
    adminer:
        container_name: adminer
        image: adminer
        restart: always
        depends_on:
            database:
                condition: service_healthy
        ports:
            - 8080:8080
        networks:
            network1:
                ipv4_address: 172.20.0.7
networks:
    network1:
        ipam:
            driver: default
            config:
                - subnet: 172.20.0.0/24
volumes:
    pgdata:
    # backend:
