name: CI build and publish

on:
    workflow_run:
        workflows: ["Integration With Database"]
        types:
            - completed
env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

jobs:
    build-and-push-image:
        runs-on: ubuntu-latest
        environment: build_and_publish
        strategy:
            fail-fast: false
            matrix:
                platform:
                    - linux/amd64
                    - linux/arm64
        steps:
            - name: Prepare
              run: |
                  platform=${{ matrix.platform }}
                  echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Log in to the Container registry
              uses: docker/login-action@v2
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.PUBLISH_PAT }}
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
              with:
                  buildkitd-flags: --debug
            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
              with:
                  images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
            - name: Build and push by digest
              id: build
              uses: docker/build-push-action@v5
              with:
                  context: ./backend
                  platforms: ${{ matrix.platform }}
                  labels: ${{ steps.meta.outputs.labels }}
                  tags: ${{ steps.meta.outputs.tags }}
                  outputs: type=image,name=${{ env.REGISTRY_IMAGE }},push-by-digest=true,name-canonical=true,push=true
                  cache-from: type=gha,scope=build-${{ env.PLATFORM_PAIR }}
                  cache-to: type=gha,scope=build-${{ env.PLATFORM_PAIR }}
